### ISSUE TITLE
不能正常工作 

### ISSUE THREAD

**Issue by xoyu** [gantoday/laravel-blog#2]
问题出在tag上
去掉tag的相关代码则正常了

ErrorException in Repository.php line 364:
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags' (View: D:\wamp\www\laravel-blog-5\resources\views\home\layout.blade.php) (View: D:\wamp\www\laravel-blog-5\resources\views\home\layout.blade.php)

**Comment by gantoday** [comment]
@xoyu 你好,因为使用了tag缓存,所以需要支持tag标签缓存的缓存系统才可以正常使用.
文件缓存和数据库缓存是不支持的,所以会出错.推荐使用redis 或者 memcache 做缓存.
当然,如果你一定要用文件缓存或者数据库缓存,修改tag相关处就行了.
有什么问题欢迎提出一起讨论.

**Comment by xoyu** [comment]
@gantoday 最好还是能在配置里选择缓存方式
我大概试了一下 希望能完善
