### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by husnulhamidiah** [gantoday/laravel-blog#3]
Some error in `@include('home.partials.sidebar')` code in layout.blade.php
It show message..

    call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags' (View: C:\xampp\htdocs\larablog\resources\views\home\layout.blade.php) (View: C:\xampp\htdocs\larablog\resources\views\home\layout.blade.php)

If I remove those line. The app works just fine.

This error also found when accessing /admin/articles/create

    call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags'

**Comment by gantoday** [comment]
redis or memcache cache is required.

**Comment by yaoshanliang** [comment]
看到代码composer中有安装predis，应该怎么启动服务

**Comment by gantoday** [comment]
@yaoshanliang 服务器安装有Redis就行,最好用homestead测试

**Comment by yaoshanliang** [comment]
如果用homestead的话，到时候部署到线上要注意很多问题了吧，服务器上安装一个virtualbox不太合适吧

**Comment by yaoshanliang** [comment]
不错不错，下面的调试栏是怎么出来的？

**Comment by gantoday** [comment]
@yaoshanliang 一个包 barryvdh/laravel-debugbar
